import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Toaster } from "react-hot-toast"

import Header from "@/components/header/Header"
import Footer from "@/components/footer/Footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "ShowUP",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          antialiased
          min-h-screen
          flex
          flex-col
        `}
      >
        <Toaster position="bottom-right" toastOptions={{ duration: 2000 }} />

        {/* Header always at top */}
        <Header />

        {/* Main content grows */}
        <main className="flex-1">
          {children}
        </main>

        {/* Footer always pushed to bottom */}
        <Footer />
      </body>
    </html>
  )
}
